### PR TITLE
Added LinkedIn Icon

### LINKED ISSUE #122: Adding Linkedin icon to Footer
### Description

* Add Linkedin icon to the footer. 
* Apply appropriate padding or margin for adjusting this extra icon on all screen sizes.
* HG Linkedin account link - https://www.linkedin.com/company/hgiiitranchi/
Note - Icon needs to be a static svg icon . Can be downloaded from https://fontawesome.com/icons?d=gallery&q=linkedin . 

### Concerning Folder
https://github.com/houseofgeeks/hg/tree/front-end/client/src/components/Footer

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>
NA

### PR DESCRIPTION
**Pull request by SaravgiYash**
fixes #122 
<Do not delete this template>
Description: Added LinkedIn Icon

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
<provide a relevant screenshot or any testimonial for the solved issue if applicable>

### CODE REVIEW

**Review by tusharjain0022 — APPROVED** [review]
LGTM 👍 , over to you @ankiiitraj @hariom1625 @EmperorYP7 .

**Review by EmperorYP7 — APPROVED** [review]
LGTM.. Thanks for your contribution @Yashs911! 😄

**Comment by hariom1625** [comment]
LGTM!!

**Review by hariom1625 — APPROVED** [review]

**Review by ankiiitraj — APPROVED** [review]

**Comment by ankiiitraj** [comment]
Just pull the changes resolve the conflict and push!
And you're good to go! @Yashs911

**Comment by SaravgiYash** [comment]
@ankiiitraj "git pull --rebase upstream front-end"??

**Comment by ankiiitraj** [comment]
> @ankiiitraj "git pull --rebase upstream front-end"??

Yup, that will do the magic!
This'll ask to resolve conflicts.

**Comment by SaravgiYash** [comment]
I guess I did something wrong.

**Comment by ankiiitraj** [comment]
I think you deleted the current changes! Nonetheless, you can copy-paste that code again and push!

**Comment by ankiiitraj** [comment]
@Yashs911, You can also contribute by reporting issues and bugs and reviewing PRs.

**Comment by ankiiitraj** [comment]
@all-contributors please add @Yashs911 for Code

**Comment by SaravgiYash** [comment]
@ankiiitraj when I try to open the website using npm start I am getting this error ./src/components/Admin/Admin.jsx
Module not found: Can't resolve 'jwt-decode' in 'C:\Users\yashs\Desktop\GitHub\hg\client\src\components\Admin'.

**Comment by ankiiitraj** [comment]
> @ankiiitraj when I try to open the website using npm start I am getting this error ./src/components/Admin/Admin.jsx
> Module not found: Can't resolve 'jwt-decode' in 'C:\Users\yashs\Desktop\GitHub\hg\client\src\components\Admin'.

Use `npm install` and it will be fine.
In the previous commit, I added 2 new packages.

**Review by ankiiitraj — APPROVED** [review]

**Pull request merged**
