### PR TITLE
admin event mainupulation

### LINKED ISSUE #43: Create admin events controller component
### Description
<write your description> 
This component will contain

- Different events posted.
- Admin should be able to create an event 
- Admin should be able to edit or delete any event 
- Pagination should be there.
 

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

### PR DESCRIPTION
**Pull request by ankiiitraj**
### Fixes #43
<Do not delete this template>
Description: <provide a description> Compelteed the Event manipulation feature!

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [ ] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
visit /admin
Thorough checking is required for finding bugs if any!

### CODE REVIEW

**Review by prskid1000 — APPROVED** [review]

**Review by vishalvibes — APPROVED** [review]
For now, it seems fine...there are a few things to be changed but I guess we will be opening those as beginner issues

**Review by hariom1625 — APPROVED** [review]
Nicely done, Great work :-)

As of now, the event section is loading only five events and I think it is because we are using the same event component as rendered in the home page, and the separate event page is on progress so not considering it here.

**Review by tusharjain0022 — APPROVED** [review]
LGTM !! 🤩 
Minor changes required but I think styling part can be done via another issue/PR like adding margin here Screenshot (22) 
and fixing font-color and some typo
Screenshot (21)

**Review by EmperorYP7 — APPROVED** [review]
LGTM! Nicely done @ankiiitraj! 🤩

**Comment by ankiiitraj** [comment]
Anyone please open an issue for fixing some of the styles that I was not able to perfectly implement!

**Pull request merged**
