### PR TITLE
completed implementation of message sending feature

### LINKED ISSUE #174: Create contact form endpoint on backend
N/A

### PR DESCRIPTION
**Pull request by ankiiitraj**
### fixes #174
<Do not delete this template>
Description: <provide a description> Added implementation of message sending feature

P.S: This should be reviewed after #175 
P.S.S @tusharjain0022  or @hariom1625 Can you please fix the css of the form.

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [ ] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
~To be updated~ https://deploy-preview-176--houseofgeeks.netlify.app/

### CODE REVIEW

**Comment by hariom1625** [comment]
Sure, I will make a PR in your repo fixing the CSS :-)

PS: I have directly made a commit in your repo, please review it and tell, is that fine?

**Comment by ankiiitraj** [comment]
@hariom1625 That's great!
Have a look at this too
Slight improvements required
ezgif com-video-to-gif(2)

**Comment by hariom1625** [comment]
> @hariom1625 That's great!
> Have a look at this too
> Slight improvements required

@ankiiitraj Have a look at it again. 

PS: I committed the changes directly so wasn't able squash them 😅

**Comment by ankiiitraj** [comment]
@EmperorYP7 @tusharjain0022 Thoughts on design.
Click on submit to see the message!

**Review by tusharjain0022 — COMMENTED** [review]
Design Looks good to me ! 💯

**Comment by EmperorYP7** [comment]
Looks nice! 🤩

**Pull request merged**
