### PR TITLE
Removing dummy text

### LINKED ISSUE #125: Lorem Epsum
### Description
- Collect the content for the landing page and update Lorem Epsum.
- Add the appropriate logos of different communities.
### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

### PR DESCRIPTION
**Pull request by EmperorYP7**
Fixes #125 
<Do not delete this template>
Description: <provide a description> Updated the community section with relevant text and removed all the console errors throughout the website.

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
<provide a relevant screenshot or any testimonial for the solved issue if applicable>

https://deploy-preview-209--houseofgeeks.netlify.app

### CODE REVIEW

**Comment by ankiiitraj** [comment]
I think we should also update the respective logos of communities in this PR itself

**Comment by tusharjain0022** [comment]
Suggestion : For the communities whose logos are not designed yet , we can replace them with the House of Geeks logo for now.

**Review by tusharjain0022 — APPROVED** [review]
LGTM! 🚀

**Review by ankiiitraj — APPROVED** [review]
LGTM

**Review by hariom1625 — APPROVED** [review]
LGTM :-)

**Comment by EmperorYP7** [comment]
Merging this..

**Pull request merged**
