### PR TITLE
chore: Fixed CP members alignment

### LINKED ISSUE #235: [Members] Fix the CSS for certain Communities
### Description
You would notice that there is a certain way of ordering members such that Community Heads are above the Coordinators and same level members are, well, at the same height. This is not the case with Competitive Coding Community.  Try to fix this.

### PR DESCRIPTION
**Pull request by abhishekrathi16**
### Fixes #235 
<Do not delete this template>
Description: The issue with the styling regarding competitive programming members appearing in a column rather than a row has been updated. The issue was directly linked with the component of Cp members itself, so I had to update it completely. It has been fixed now.

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
<provide a relevant screenshot or any testimonial for the solved issue if applicable>

hog

### CODE REVIEW

**Review by EmperorYP7 — APPROVED** [review]
LGTM

**Review by hariom1625 — APPROVED** [review]
LGTM!

**Review by himanshu007-creator — APPROVED** [review]
LGTM🎉

**Comment by EmperorYP7** [comment]
@abhishekrathi16 @himanshu007-creator Thanks for the contribution! 🤝 Don't forget to star this repo if you liked this project. ⭐️

**Pull request merged**
