### PR TITLE
Remove navbar hamburger white background

### LINKED ISSUE #86: Hamburger icon looking different on mobile browser
### Description
<write your description> Hamburger icon is rendering with white background color on my mobile browser(chrome) while it needs to be transparent.
Note - This is not visible on chrome developers tool or FireFox ,so while debugging, it needs to be tested on real mobile phone by connecting it on same Wifi connection and then browsing with `<PC/Laptop's IP address>:<Port number>` on mobile browser.

### Concerning Folder 
 https://github.com/houseofgeeks/hg/tree/front-end/client/src/components/Navbar

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

WhatsApp Image 2020-09-24 at 8 11 06 PM

### PR DESCRIPTION
**Pull request by jamesjlundin**
fixes #86 
<Do not delete this template>
Description:  Remove white background on mobile hamburger icon The title should be short and relevant.

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
I deployed my fix to netlify to test on an actual smart phone can be viewed at link below:
https://relaxed-bohr-8e81c8.netlify.app/

### CODE REVIEW

**Review by EmperorYP7 — APPROVED** [review]
LGTM. Great to have your contribution @thecodediver! 😄

**Review by ankiiitraj — APPROVED** [review]

**Comment by ankiiitraj** [comment]
Thanks for the PR @thecodediver 🎉

**Comment by ankiiitraj** [comment]
@all-contributors please add @thecodediver

**Comment by ankiiitraj** [comment]
@all-contributors please add @thecodediver for code

**Pull request merged**
