### PR TITLE
Added a warning message

### LINKED ISSUE #187: Add a warning before deleting anything in admin panel
Add a warning (confirmation pop up) that comes before deleting anything in the admin panel

### PR DESCRIPTION
**Pull request by ankiiitraj**
### Fixes #187
<Do not delete this template>
Description: Added warning before deleting an Event for Admin.

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [ ] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
~to be updated~ https://deploy-preview-190--houseofgeeks.netlify.app/

### CODE REVIEW

**Review by EmperorYP7 — APPROVED** [review]
LGTM!

**Comment by tusharjain0022** [comment]
LGTM!
I think this typo can be fixed in this issue. For changing time first use backspace ~they~ then enter number or use arrow keys
Screenshot (21)
And in edit mode slash symbol gets disappeared in the date and time input box or its text color changes to white.

**Review by tusharjain0022 — COMMENTED** [review]
LGTM!
I think this typo can be fixed in this issue. For changing time first use backspace ~they~ then enter number or use arrow keys
Screenshot (21)
And in edit mode slash symbol gets disappeared in the date and time input box or its text color changes to white.

**Comment by hariom1625** [comment]
Two pop-up messages are being displayed when an event deletion action is performed. Is that intentional @ankiiitraj ?
Everything else LGTM !!

**Review by hariom1625 — APPROVED** [review]

**Comment by ankiiitraj** [comment]
That's not intentional but don't have substitute currently!

**Pull request merged**
