### PR TITLE
[Feat] Close the navbar on `esc` keypress #144

### LINKED ISSUE #144: Close the navbar on `esc` keypress
### Screenshots/testimonials
N/A

### PR DESCRIPTION
**Pull request by dineshsy**
fixes #144 
<Do not delete this template>
Description: Fixed: Close the navbar on `esc` keypress

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
N/A

### CODE REVIEW

**Review by ankiiitraj — APPROVED** [review]

**Review by EmperorYP7 — APPROVED** [review]
LGTM! Thanks for your contribution @dineshsy! :+1:

**Comment by EmperorYP7** [comment]
@all-contributors please add @dineshsy for code.

**Comment by EmperorYP7** [comment]
Merging this upon clearance.

**Comment by ankiiitraj** [comment]
> Merging this upon clearance.

whoops

**Pull request merged**
