### PR TITLE
Add Community Section

### PR DESCRIPTION
**Pull request by sj00coder**
fixes #<number>
<Do not delete this template>
Description: <provide a description> The title should be short and relevant.

#### Checklist
- [ x ] I've followed the Contributing guidelines provided in the repository.
- [ x ] I've made the changes which were demanded in the linked issue.
- [ x ] I've tested my code on a Chromium based browser.
- [ x ] I've tested my code on Mozilla Firefox.
- [ x ] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
I have created a community section in components folder.

### CODE REVIEW

**Comment by ankiiitraj** [comment]
@EmperorYP7 Check this and guide @sj00coder.
I am seeing a lot of files!
BTW congrats on your first contribution! Yaay

**Review by EmperorYP7 — CHANGES_REQUESTED** [review]
Looks like the whole front-end part is missing. Kindly pull all the changes of `houseofgeeks:front-end` to your local repo's front-end branch and make the changes in the concerned files. After you've completed your work, push the whole thing onto `sj00coder:front-end` and make a pull request for that.

**Comment by sj00coder** [comment]
> Looks like the whole front-end part is missing. Kindly pull all the changes of `houseofgeeks:front-end` to your local repo's front-end branch and make the changes in the concerned files. After you've completed your work, push the whole thing onto `sj00coder:front-end` and make a pull request for that.

Sorry for that.

**Comment by sj00coder** [comment]
> Looks like the whole front-end part is missing. Kindly pull all the changes of `houseofgeeks:front-end` to your local repo's front-end branch and make the changes in the concerned files. After you've completed your work, push the whole thing onto `sj00coder:front-end` and make a pull request for that.

Sir my front-end branch is up to date and have all the files and it also has nothing to commit.What should I do now?Please guide sir

**Comment by EmperorYP7** [comment]
That's great @sj00coder! 🤩  You've got it.. Just make the changes you've done in `sj00coder:Commbrh` to `sj00coder:front-end` in the [relevant files](https://github.com/houseofgeeks/hg/tree/front-end/client/src/components/Home/CommunitySection) and create a pull request to `houseofgeeks:front-end` from `sj00coder:front-end` and you're good to go!

**Comment by ankiiitraj** [comment]
Closing this as the issue has been closed

**Pull request closed without merging**
