### PR TITLE
HG logo fix on landing page

### LINKED ISSUE #77: Hg logo looks messed
### Description
While scrolling in smaller screens the Hg logo gets overlapped by letters which looks bad!
My initial thoughts, we can make a solid background on top which will be fixed and the Hg logo will be there along with the hamburger

suggestions?

### Screenshots/testimonials
Screenshot from 2020-09-23 12-58-14

### PR DESCRIPTION
**Pull request by tusharjain0022**
fixes #77 
<Do not delete this template>
Description: <provide a description> I've removed the parallax effect on the landing page for the small devices (width<427px).

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial/Screenshot
<provide a relevant screenshot or any testimonial for the solved issue if applicable>

House of Geeks, IIIT Ranchi - Google Chrome 2020-10-04 22-27-41_Trim

WhatsApp Video 2020-09-26 at 5 51 12 PM

### CODE REVIEW

**Review by ankiiitraj — APPROVED** [review]
LGTM 🎉

**Comment by hariom1625** [comment]
In the mobile view, the astronaut's foot appears to be a bit above the surface which looks quite odd.
Screenshot (187)

**Comment by EmperorYP7** [comment]
> In the mobile view, the astronaut's foot appears to be a bit above the surface which looks quite odd.

My bad 😛

**Review by EmperorYP7 — APPROVED** [review]
LGTM!

**Comment by tusharjain0022** [comment]
> In the mobile view, the astronaut's foot appears to be a bit above the surface which looks quite odd.
> Screenshot (187)

I'll be resolving this issue in my next commit , thanks for noticing this problem.

**Review by ankiiitraj — APPROVED** [review]

**Comment by ankiiitraj** [comment]
@tusharjain0022 Is this ready to be merged?

**Comment by tusharjain0022** [comment]
Yes, I've solved the issue mentioned by @hariom1625 . You can review it now 🙌

**Review by hariom1625 — APPROVED** [review]

**Pull request merged**
