### PR TITLE
added functionality to notice section

### LINKED ISSUE #70: Add functionality to notice board
### Description
<write your description> 
Since the server is up and running. Add functionality to notice section.

api: /notice

result-format: {result: [], message: 'OK'}

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

### PR DESCRIPTION
**Pull request by ankiiitraj**
fixes #70 

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
<provide a relevant screenshot or any testimonial for the solved issue if applicable>

### CODE REVIEW

**Comment by ankiiitraj** [comment]
Someone @tusharjain0022 @EmperorYP7 can take care of the CSS. I am opening an issue for that.

**Comment by EmperorYP7** [comment]
> Someone @tusharjain0022 @EmperorYP7 can take care of the CSS. I am opening an issue for that.

No problem! 😉

**Comment by tusharjain0022** [comment]
Sure.. 🙌

**Comment by ankiiitraj** [comment]
After all working fine! Just need some css touch!

**Review by EmperorYP7 — APPROVED** [review]
LGTM! Nice work @ankiiitraj 🤩 (Must have smashed that enter key really hard to push the last commit.😂)

**Review by tusharjain0022 — APPROVED** [review]
Everything looks perfect !! LGTM 🚀

**Pull request merged**
