### PR TITLE
Fixing broken link

### PR DESCRIPTION
**Pull request by hariom1625**
### Solves Issue #26 
Description: Added netlify.toml file for setting the redirects to index.html .

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

### CODE REVIEW

**Review by EmperorYP7 — APPROVED** [review]
Clever! 💡

**Comment by EmperorYP7** [comment]
Do add this to the front-end branch as well in #21

**Comment by hariom1625** [comment]
> Do add this to the front-end branch as well in #21
I was thinking the same but since I don't know which branch is being deployed whether master or the other so, for now, I have added it only to master.
Let us see if this works or not!

**Comment by ankiiitraj** [comment]
So only front-end branch is being deployed. so make the PR in that branch

**Comment by prskid1000** [comment]
It was a good idea

**Comment by hariom1625** [comment]
Do I change the base branch of this very PR to the front-end or shall create a new PR for the front-end.

**Comment by EmperorYP7** [comment]
It would be better if you create a new PR for this.

**Comment by ankiiitraj** [comment]
Closing this against #31

**Pull request closed without merging**
