### PR TITLE
Rendering Members details in Community section also

### LINKED ISSUE #206: Render Members details of specific section in Community section also
### Description
<write your description>
Render Members details of specific section below the details of community.

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

Screenshot (58)_LI

## Expected :
screencapture-localhost-3000-electronics-iot-2020-11-05-18_07_14

### PR DESCRIPTION
**Pull request by tusharjain0022**
### Fixes #206 
<Do not delete this template>
Description: 

I've made the `CommunityTemplate` component to render details of specific community with their specific members via conditional rendering of member components.

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [ ] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial/Screenshot
<provide a relevant screenshot or any testimonial for the solved issue if applicable>

screencapture-localhost-3000-competitive-coding-2020-11-06-00_43_19

### CODE REVIEW

**Review by ankiiitraj — APPROVED** [review]
very Clean!

**Review by hariom1625 — APPROVED** [review]
Neatly done !! 

PS: I can observe a bit of an increase in width of the About us section on the homepage which doesn't look good. Have a look at it @tusharjain0022 and alter it accordingly whatever looks best to you.

**Review by EmperorYP7 — APPROVED** [review]
Well done @tusharjain0022! Clean and simple! 🤩

**Comment by tusharjain0022** [comment]
> Neatly done !!
> 
> PS: I can observe a bit of an increase in width of the About us section on the homepage which doesn't look good. Have a look at it @tusharjain0022 and alter it accordingly whatever looks best to you.

@hariom1625 Could you share screenshot about which viewpoint you're talking about as I'm unable to identify that problem here. Width seems to be normal to me

**Comment by hariom1625** [comment]
@tusharjain0022 I think I viewed the two commit in the different screen views. It seems alright to me now. My bad 😄.

**Comment by EmperorYP7** [comment]
Merging this against approvals of all reviewers. Good job @tusharjain0022! :+1:

**Pull request merged**
