### PR TITLE
added supprot for sending messages

### PR DESCRIPTION
**Pull request by ankiiitraj**
### Solves Issue #174 
<Do not delete this template>
Description: 
- Fixes bugs from the last commit.
- Added sending message feature and endpoint on the backend

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [ ] I've tested my code on a Chromium based browser.
- [ ] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
N/A

### CODE REVIEW

**Comment by ankiiitraj** [comment]
Guys @EmperorYP7 @tusharjain0022 @hariom1625 
This need to be merged for the new feature I'm working on!
Review this one!

**Comment by hariom1625** [comment]
Sorry for being late 😅
LGTM, please go ahead, excited to see the new addition !!

**Review by hariom1625 — APPROVED** [review]

**Review by tusharjain0022 — APPROVED** [review]
LGTM 🙌

**Review by EmperorYP7 — APPROVED** [review]
LGTM. Merging this.

**Pull request merged**
