### PR TITLE
added preloader

### LINKED ISSUE #60: Create design for Preloader
### Description
The design should be in the relation to the current theme!
(preloader: search on google)
### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

### PR DESCRIPTION
**Pull request by ankiiitraj**
fixes #60 
<Do not delete this template>
Description: <provide a description> Simple preloader, can be modified if something better in option!

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes that were demanded in the linked issue.
- [ ] I've tested my code on a Chromium-based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
N/A

### CODE REVIEW

**Comment by ankiiitraj** [comment]
To see the preloader in action, go to the console and then to network and choose regular 2G in throttling!

**Comment by hariom1625** [comment]
Loved it !!

**Review by tusharjain0022 — APPROVED** [review]
looks amazing !! LGTM! 🤩

**Review by EmperorYP7 — APPROVED** [review]
LGTM.. let's get this fired up! 🤩

**Pull request merged**
