### PR TITLE
added default height

### LINKED ISSUE #216: [Member] Set member image placeholder (fixed height)
### Description
Add a default width and height to the wrapper of images. See the screenshot for the issue.

### Screenshots/testimonials
Screenshot from 2020-12-26 19-57-30

### PR DESCRIPTION
**Pull request by AK-codingmaniac**
### Fixes #216 

<Do not delete this template>
Description: <provide a description> Added Default Height

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
<provide a relevant screenshot or any testimonial for the solved issue if applicable>

issu216test

### CODE REVIEW

**Comment by AK-codingmaniac** [comment]
I noticed that there was a need to add a default height in the wrapper of photos of members and it was in the issues list also so I tried to do it

**Review by tusharjain0022 — APPROVED** [review]
Looks good to me :star2: , But I would suggest we should rename this CSS file to somewhat "members.css" as it is signifying that it contains styling for only competitive-coding members section.

**Review by EmperorYP7 — COMMENTED** [review]
Great work @AK-codingmaniac! Looking forward to seeing more contributions from you. Welcome to the club! 🙌🏻

Also, don't forget to star this repo if you think this is a great project. :star:

**Comment by tusharjain0022** [comment]
@all-contributors please add @AK-codingmaniac  for code
Edit: Will need to fix this !
Edit (16:40PM Oct28) : Issue Resolved!

**Comment by tusharjain0022** [comment]
@all-contributors please add @AK-codingmaniac for code

**Pull request merged**
