### PR TITLE
Modify the event API call limit to 5

### PR DESCRIPTION
**Pull request by cod500**
### Fixes - 1 fix, issue #231
<Do not delete this template>
Description: Modify the event API call limit to 5 events.

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
The json data was already sorted from most current event to past so I just decided to limit the array size with the slice method.

### CODE REVIEW

**Review by EmperorYP7 — APPROVED** [review]
LGTM! Thanks for the contribution :tada:

**Comment by EmperorYP7** [comment]
Don't forget to star this repo if you liked this project! :smile:

@all-contributors please add @cod500 for code

**Comment by EmperorYP7** [comment]
> @EmperorYP7
> 
> This project's configuration file has malformed JSON: .all-contributorsrc. Error:: Unexpected token : in JSON at position 5176

@tusharjain0022 👀

**Comment by tusharjain0022** [comment]
@all-contributors please add @cod500  for code

**Pull request merged**
