### PR TITLE
Remaking the landing page

### LINKED ISSUE #33: Recreating the landing page
### Description

Since this website is going to be the face of our technical society, we should make the landing page as attractive as we can. With designers on board, let us stick to one theme for the entire website.

### Screenshots/testimonials

NA

### PR DESCRIPTION
**Pull request by EmperorYP7**
fixes #33 
<Do not delete this template>
Description: Recreated the landing page using vector images only for faster loading along with CSS animations and changing the theme of the website for good. This is a potential design and not definitive of being adapted into the website. Design proposed by @EricLiclair .

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial

image

### CODE REVIEW

**Comment by prskid1000** [comment]
Design looks quite good!

**Comment by EmperorYP7** [comment]
Thank you @prskid1000 :smile:

**Comment by EmperorYP7** [comment]
Sorry for being late. @ankiiitraj @prskid1000 @hariom1625 @tusharjain0022 @rishavMZ you all may review this now.

**Comment by tusharjain0022** [comment]
Everything LGTM 🔥 !!
Suggestion : if there is a little less whitespace between the asteroids and the write-up image on small screen sizes ,it would look more attractive and clean. This can also be added as another issue under the label "good first issue" .
Screenshot (396)
Screenshot (397)

**Comment by ankiiitraj** [comment]
Awsome work @EmperorYP7  and @EricLiclair 
There's horizontal overflow!
Overall it looks perfect.
These small tweaks and you're good to go!
I did some intercepts here how it looks!
ezgif-1-1f3e7ebeee98

**Comment by EmperorYP7** [comment]
Nice observation @tusharjain0022! It was really an overkill for me to fix that. It should be fixed when more sections will be added.

**Comment by EmperorYP7** [comment]
@ankiiitraj should I remove footer's background? or something else?

**Comment by ankiiitraj** [comment]
> @ankiiitraj should I remove footer's background? or something else?

Not an expert in degins, you guys decide whatever looks good!

**Comment by hariom1625** [comment]
The radius of the top right circle can be reduced a bit as it Is overlapping with the word GEEKS and due to its size it is being highlighted a bit more than other components.
And in the animation where the guy free falls, the shadow below his foot is being visible while that guy is still in the air, you can fix that too i.e, making the shadow visible after it reaches the surface.
Everything else LGTM! 🎉

**Comment by EmperorYP7** [comment]
> The radius of the top right circle can be reduced a bit as it Is overlapping with the word GEEKS and due to its size it is being highlighted a bit more than other components.

How does it look now? Btw, screens larger than 1300 px wide will have the planet overwhelming "GEEKS". This is intensional though. Besides, I am working on that animation. Good that you pointed it out! 🤩  @hariom1625 

image

**Comment by hariom1625** [comment]
> > The radius of the top right circle can be reduced a bit as it Is overlapping with the word GEEKS and due to its size it is being highlighted a bit more than other components.
> 
> How does it look now? Btw, screens larger than 1300 px wide will have the planet overwhelming "GEEKS". This is intensional though. @hariom1625
> 
> image

I think you can set the z-index value of the circular vector element such that it makes the circle look behind the other elements i.e static in the background, in that case having the previous size will also work fine.

**Comment by EmperorYP7** [comment]
Fixed it @hariom1625. Also, the z-index of planet had no effect on the screen. I think I should be using some colour manipulators in CSS.

**Comment by ankiiitraj** [comment]
LGTM, 
Reviewers @ankiiitraj @tusharjain0022 and @hariom1625 
Merging

**Pull request merged**
