### PR TITLE
contactUs section update

### LINKED ISSUE #110: Show contact us form only on the landing page
### Description
As discussed here #105 

### Screenshots/testimonials

N/A

### PR DESCRIPTION
**Pull request by tusharjain0022**
fixes #110 
<Do not delete this template>
Description: <provide a description> I've made the contact-us component to render on home page only.

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
<provide a relevant screenshot or any testimonial for the solved issue if applicable>
NA

### CODE REVIEW

**Review by ankiiitraj — APPROVED** [review]
That's neat! 🎉

**Comment by hariom1625** [comment]
Screenshot (171

In the mobile view, the footer seems a bit more compact as the icons are being superposed over the footer-background, a bit of padding, and margin can be added on the icons for the mobile view.

I tried a bit of experiment see if it looks good
Screenshot (170

PS: Have added margin across the icons for resolution less than 767px.

**Comment by EmperorYP7** [comment]
> In the mobile view, the footer seems a bit more compact as the icons are being superposed over the footer-background, a bit of padding, and margin can be added on the icons for the mobile view.
> 
> I tried a bit of experiment see if it looks good
> 
> PS: Have added margin across the icons for resolution less than 767px.

Also, we should be adding the LinkedIn handle of hG as well! 😄

**Review by EmperorYP7 — APPROVED** [review]
LGTM.
However look at the community page in the deployment. Looks a bit messed up. But, we'll cover that in a new issue.

**Review by hariom1625 — APPROVED** [review]

**Comment by tusharjain0022** [comment]
> Screenshot (171
> 
> In the mobile view, the footer seems a bit more compact as the icons are being superposed over the footer-background, a bit of padding, and margin can be added on the icons for the mobile view.
> 
> I tried a bit of experiment see if it looks good
> Screenshot (170
> 
> PS: Have added margin across the icons for resolution less than 767px.

This looks good , I think we can create another issue for that and can also add the Linked-in icon in it.. For the community section , I've found a fix let me make a commit for it .

**Review by EmperorYP7 — APPROVED** [review]
Perfect 💯

**Review by ankiiitraj — APPROVED** [review]

**Pull request merged**
