### PR TITLE
UI breaking fixed

### LINKED ISSUE #212: Change default display picture of members!
The current DP doesn't look formal. Change the DP to something formal!

### LINKED ISSUE #213: UI breaking until the events have not arrived
### Description
A fix is to give the events component a min height of some pixels!

I tried with 700px and it worked!

Screenshot from 2020-12-16 12-36-11

### PR DESCRIPTION
**Pull request by tusharjain0022**
### Fixes #212, #213 
<Do not delete this template>
Description: <provide a description>

I've fixed the breaking of the UI while fetching the events detail from the backend by adding a minimum height to the event component on the home page as suggested by @ankiiitraj , but instead of adding 700px , I used 100vh as minimum height because at large screen width 700px was not getting the desired result.

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
<provide a relevant screenshot or any testimonial for the solved issue if applicable>

Screenshot (134)

### CODE REVIEW

**Review by hariom1625 — CHANGES_REQUESTED** [review]
@tusharjain0022 Have a look at this, the content is getting cornered to the right leaving a lot of blank space in the middle which is looking a bit odd maybe the planet size can be reduced a bit and shifted to the left giving more space for the event list.

**Comment by tusharjain0022** [comment]
I'll look into it.

**Comment by EmperorYP7** [comment]
Still looks a bit off to me @tusharjain0022 
Screenshot 2020-12-24 at 8 11 13 PM

**Comment by ankiiitraj** [comment]
Seems this lil planet is being very mischievous...

**Comment by tusharjain0022** [comment]
@EmperorYP7 How's this ? Actually positioning the Planet in the center is leaving very little space for the Events list 
## 1 (shifting planet to left)
Screenshot (161)

## 2 (shifting union.svg to community section and increase width of event list)
Screenshot (163)
Screenshot (164)

**Comment by EmperorYP7** [comment]
> How's this ? Actually positioning the Planet in the center is leaving very little space for the Events list

I would prefer 2. What do you say @hariom1625 and @ankiiitraj?

**Comment by hariom1625** [comment]
> I would prefer 2. What do you say @hariom1625 and @ankiiitraj?

Design (2) LGTM !!

**Comment by ankiiitraj** [comment]
The second one looks great

**Review by ankiiitraj — APPROVED** [review]
lgtm

**Review by EmperorYP7 — COMMENTED** [review]
Screenshot 2020-12-26 at 8 05 54 PM

Here the text isn't aligned properly

Screenshot 2020-12-26 at 8 06 15 PM

Here `union.svg` is overflowing the containing component.

**Review by EmperorYP7 — APPROVED** [review]
LGTM!

**Review by hariom1625 — APPROVED** [review]
LGTM !!

**Pull request merged**
