### PR TITLE
[back-end] Adding Express.js

### PR DESCRIPTION
**Pull request by EmperorYP7**
### Solves Issue #1 
Description: With reference to #4 and #5 , making relevant changes to this branch. (view engine to be modified soon)

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
NA

### CODE REVIEW

**Comment by ankiiitraj** [comment]
I see there is a node_modules folder that shouldn't be there. Sanitise that

**Review by ankiiitraj — CHANGES_REQUESTED** [review]
delete the node_modules folders

**Comment by EmperorYP7** [comment]
> delete the node_modules folders

I am on it.

**Comment by ankiiitraj** [comment]
There are still node_modules folder inside backend

**Review by ankiiitraj — APPROVED** [review]

**Pull request merged**
