### PR TITLE
Cleaning up images folder

### LINKED ISSUE #214: Cleaning up the images folder
### Description
<write your description> There is an obvious need to restructure or rather organise the [images folder](https://github.com/houseofgeeks/hg/tree/front-end/client/public/images) for better navigation and upgradability of members and other assets.

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>
NA

### PR DESCRIPTION
**Pull request by sb2356-iiitr**
### Fixes #214 
<Do not delete this template>
Description: Reorganising Images
I have reorganised the images into various folders like Communities, Sponsors and Members.

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial

image

### CODE REVIEW

**Comment by EmperorYP7** [comment]
@sb2356-iiitr looks like you've used GUI for this. (even atomic changes were committed)
Also, if you restructured the images folder, you also need to update the include path of these images in various components. For instance,

Screenshot 2020-12-28 at 1 32 04 PM

Here, the path to various logos isn't updated in [`PartnersList.js`](https://github.com/houseofgeeks/hg/blob/front-end/client/src/components/Home/PartnersSection/PartnersList.js).

Kindly look for every include path and update it as needed.

**Review by EmperorYP7 — CHANGES_REQUESTED** [review]
@sb2356-iiitr looks like you've used GUI for this. (even atomic changes were committed)
Also, if you restructured the images folder, you also need to update the include path of these images in various components. For instance,

Screenshot 2020-12-28 at 1 32 04 PM

Here, the path to various logos isn't updated in [`PartnersList.js`](https://github.com/houseofgeeks/hg/blob/front-end/client/src/components/Home/PartnersSection/PartnersList.js).

Kindly look for every include path and update it as needed.

**Comment by sb2356-iiitr** [comment]
Understood, thanks

**Review by EmperorYP7 — APPROVED** [review]
LGTM!
Great work @sb2356-iiitr! 🥳

**Comment by sb2356-iiitr** [comment]
Thank you @EmperorYP7 :smile:

**Comment by ankiiitraj** [comment]
Looks good to me!

**Review by ankiiitraj — APPROVED** [review]
lgtm

**Comment by sb2356-iiitr** [comment]
Thank you @ankiiitraj :smile:

**Comment by ankiiitraj** [comment]
@all-contributors please add @sb2356-iiitr  for code

**Pull request merged**
