### PR TITLE
Refactoring file structure

### PR DESCRIPTION
**Pull request by EmperorYP7**
### Solves Issue #11 
Description: Created a basic file structure for the frontend part of the project with consideration of flexibility to manipulate this in the future.

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
Overview
image

Clean console
image

### CODE REVIEW

**Review by ankiiitraj — APPROVED** [review]
the standard is using lowercase letters with '-' for jsx classNames.
Correct me if I'm wrong.
Rest LGTM

**Comment by EmperorYP7** [comment]
> the standard is using lowercase letters with '-' for jsx classNames.
> Correct me if I'm wrong.
> Rest LGTM

I think there are many conventions for that. `class-name` and `ClassName` both are used in official documentation of React and other projects.
[This page](https://stackoverflow.com/questions/57221878/react-classname-naming-convention) gives more information about this.

**Comment by ankiiitraj** [comment]
we're using bootstrap which uses lowercase for classes and for consistency will be using lowercase.
Make the changes are you are good to go

**Review by ankiiitraj — APPROVED** [review]

**Comment by prskid1000** [comment]
LGTM

**Review by prskid1000 — APPROVED** [review]

**Pull request merged**
