### PR TITLE
Adding Community section

### PR DESCRIPTION
**Pull request by sj00coder**
fixes #46 
<Do not delete this template>
Description: <provide a description> The title should be short and relevant.

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
<provide a relevant screenshot or any testimonial for the solved issue if applicable>

### CODE REVIEW

**Comment by EmperorYP7** [comment]
Woops, I think you should go for creating pull request to `houseofgeeks:front-end` instead of back-end.

**Comment by ankiiitraj** [comment]
Hi @sj00coder I'll suggest you to go through the documentation once! 
Then you can ask your doubts here!

**Comment by EmperorYP7** [comment]
Absolutely, we can have a conversation on slack as well! :smile:

**Comment by ankiiitraj** [comment]
Closing this as the issue has been resolved!
Reopen this if required!

**Pull request closed without merging**
