### PR TITLE
Changes to Event Component

### LINKED ISSUE #108: Events page mobile view bug
### Description
`Event` hides behind the hamburger icon.
Checkout screenshot attached

### Screenshots/testimonials

Screenshot from 2020-09-27 13-57-27

### PR DESCRIPTION
**Pull request by NiketanG**
fixes #108

Description: Updated Event Component to fix layout and position

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
Screenshot_2020-10-03-01-24-42-653_com android chrome
Screenshot from 2020-10-03 01-25-07

### CODE REVIEW

**Comment by tusharjain0022** [comment]
planet.svg gets overlapped with the about-us content on screen width less than 620px (refer to the screenshot attached below)

Screenshot (453)



 oops!! looks like something got messed up here.

Screenshot (454)

**Comment by NiketanG** [comment]
@tusharjain0022 My bad. Will be fixed in next commit.

**Comment by tusharjain0022** [comment]
@NiketanG any updates on this PR!!? union.svg (that pink partition line for community section starting from notice) still not rendering as per our [wireframe](https://www.figma.com/file/WKIfra7Dxh033gwNoRikh6/House-of-Geeks-(Copy)), and planet is not visible on small devices else everything looks nice . Let us know if you require any help .
Screenshot (456)
Screenshot (459)

## Expected :
Screenshot (460)

**Comment by NiketanG** [comment]
@tusharjain0022 Is it fine now ?

**Comment by ankiiitraj** [comment]
LGTM over to you @tusharjain0022 and @EmperorYP7

**Review by EmperorYP7 — CHANGES_REQUESTED** [review]
image
Kindly fix this.

**Comment by hariom1625** [comment]
> Kindly fix this.
Along with this look over to the lower end of the vertical line, for a large resolution screen, it is going crossing the partner's section.

**Comment by hariom1625** [comment]
> Kindly fix this.

Along with this also have a look over the lower end of the vertical line, for a large resolution screen, it is crossing the partner's section.

**Comment by NiketanG** [comment]
> > Kindly fix this.
> 
> Along with this also have a look over the lower end of the vertical line, for a large resolution screen, it is crossing the partner's section.

The Starting positioning can be fixed by moving the line component into Events Component. But, there's no possible way to calculate sufficient height that will be appropriate for any view port as the size of the content (on homepage) change based on height as well as width. So we'll have to hard code most height values, based on browser width. I'll try to get as close as I can, but it'll probably be off by a few pixels on some devices.

**Comment by NiketanG** [comment]
@EmperorYP7 @hariom1625 Recheck.

**Comment by hariom1625** [comment]
@NiketanG You can visit the current state of the website at (https://houseofgeeks.netlify.app/) and can view the About us section.
You can add your creativity too but the basic design should resemble the current one. But I can see your code has so many bugs and a lot of breakpoints when we switch the screen resolutions.
So I will suggest you to thoroughly go through the design once for different screen resolutions and make the changes in your code accordingly.

**Comment by NiketanG** [comment]
@hariom1625 Would you mind telling me where exactly the issue is ? I can't check on all screen sizes, so if you specify the sizes on which the issue is present I could fix it.

**Comment by ankiiitraj** [comment]
Screenshot from 2020-10-06 13-06-56
We generally check on these screen sizes.

**Comment by NiketanG** [comment]
@ankiiitraj @hariom1625 Check again. I've tested with the list of devices you provided, and there weren't any issues

**Comment by EmperorYP7** [comment]
@NiketanG the planet should be in the same place as it is in the actual website right now. This is completely intensional and part of the design which we must retain. You may add custom break points to adjust the planet's position at different screen sizes.

**Comment by NiketanG** [comment]
> @NiketanG the planet should be in the same place as it is in the actual website right now. This is completely intensional and part of the design which we must retain. You may add custom break points to adjust the planet's position at different screen sizes.

On the home page, right ? Mind sending a screenshot so I'd know where exactly to change

**Comment by tusharjain0022** [comment]
## Wireframe Link 
https://www.figma.com/file/WKIfra7Dxh033gwNoRikh6/House-of-Geeks-(Copy)?node-id=0%3A1

## Mobile Screen 
Screenshot (473)

### Expected
Screenshot (460)

## Desktop

Screenshot (474)
 
### Expected
Desktop - 1

**Comment by NiketanG** [comment]
@EmperorYP7 I've done some changes, take a look

**Review by ankiiitraj — APPROVED** [review]
Thank you for doing the iterations! Over to you @EmperorYP7

**Review by tusharjain0022 — APPROVED** [review]
LGTM !! Nice work @NiketanG 💯

**Comment by hariom1625** [comment]
Refer to the below screenshots the issue is for iPad, iPad pro, and surface duo, the event section text is overflowing the about us section. And the vertical line should go till the end of the community section, have a look at it too. 
Everything else looks good to me. Nice work @NiketanG !!



Screenshot (190)

**Comment by NiketanG** [comment]
@hariom1625 Done.

**Comment by ankiiitraj** [comment]
This PR is here for a while now! @EmperorYP7 @hariom1625 take this as a priority for now.
Thanks, again @NiketanG

**Comment by hariom1625** [comment]
@ankiiitraj You can go ahead and merge the PR. The PR LGTM !! 
Nice work @NiketanG

**Review by hariom1625 — APPROVED** [review]

**Pull request merged**
