### PR TITLE
Added text in preloader

### LINKED ISSUE #99: Add text to preloader
### Description
Add text `Loading . . .` to the preloader.

Ask doubts in the comments!

### Screenshots/testimonials
N/A

### PR DESCRIPTION
**Pull request by SaravgiYash**
fixes #99 
<Do not delete this template>
Description: Added loading text

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
<provide a relevant screenshot or any testimonial for the solved issue if applicable>

### CODE REVIEW

**Review by tusharjain0022 — COMMENTED** [review]
Some minor modifications required and you're good to go . I would suggest to add some margin-top to the text . And the text doesn't seems to be well aligned on small screen as it is on large screens.

Screenshot (439)

**Comment by hariom1625** [comment]
Adding to @tusharjain0022 suggestions, also try to make the loader screen fit to screen as for small size scrolling option i.e scroll bar is being visible.

**Comment by SaravgiYash** [comment]
@tusharjain0022 @hariom1625 can you guys please check if my latest commit resolves the issue?

**Comment by hariom1625** [comment]
Yes, @Yashs911 I reviewed your commit just add some more margin to the top of the text (try adding ```margin-top:25px``` ) you can also remove the ```margin``` property it won't make any difference.

**Review by EmperorYP7 — APPROVED** [review]
LGTM

**Review by hariom1625 — APPROVED** [review]
LGTM!!

**Review by tusharjain0022 — APPROVED** [review]
LGTM too !!🤩

**Pull request merged**
