### PR TITLE
Added quote in the footer

### LINKED ISSUE #97: Add quote in the footer
### Description
Add the quote `Made with ❤️ and open-sourced` or something like this in the footer

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

### PR DESCRIPTION
**Pull request by SaravgiYash**
fixes #97 
<Do not delete this template>
Description: Added quote as requested

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
<provide a relevant screenshot or any testimonial for the solved issue if applicable>

### CODE REVIEW

**Review by EmperorYP7 — COMMENTED** [review]
The implementation is correct however, this line still seems unnecessary to me. What do you all think? @ankiiitraj @hariom1625 @tusharjain0022

**Comment by hariom1625** [comment]
> The implementation is correct however, this line still seems unnecessary to me. What do you all think? @ankiiitraj @hariom1625 @tusharjain0022

It looks fine to me !!

**Review by ankiiitraj — APPROVED** [review]

**Comment by ankiiitraj** [comment]
Everythings look good. @Yashs911 can you use this `❤` instead in `red` color

**Comment by ankiiitraj** [comment]
Thanks for the PR @Yashs911

**Pull request merged**
